In [1]:
import numpy as np
import cv2
import tensorflow as tf 

In [2]:
print(tf.__version__)

2.8.0-dev20211203


In [7]:
automl_model_path = "/Users/clement/Desktop/bluelens/automl/model-6365926034218418176/tflite/2022-01-05T08:16:43.353146Z/model.tflite"

In [9]:
import tensorflow as tf

# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path=automl_model_path)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

In [9]:
# Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.uint8)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

In [68]:
# OpenCV read image to Numpy
img_test_path = "/Users/clement/Desktop/bluelens/automl/zz_astropi_1_photo_189.jpg"
img_test = cv2.imread(img_test_path)
img_test = cv2.resize(img_test,(512,512)) # resizing using cv2.resize method
img_test_np = img_test.astype(np.uint8)
print(img_test_np.shape)


# PIL open image to Numpy
from PIL import Image
img_pil = Image.open(img_test_path)
img_pil = img_pil.resize((512,512)) # resizing using PIL img.resize method
img_pil_np = np.array(img_pil)
print(img_pil_np.shape)

(512, 512, 3)
(512, 512, 3)


In [1]:
def prepare_image(img_path):
  img = cv2.imread(img_path)
  img = cv2.resize(img,(512,512)) # resizing using cv2.resize method
  img_np = img.astype(np.uint8)
  return img_np

In [4]:
import cv2 
import numpy as np
img_path_1 = "/Users/clement/Desktop/bluelens/automl/zz_astropi_1_photo_189.jpg"
img_path_2 = "/Users/clement/Desktop/bluelens/automl/zz_astropi_1_photo_190.jpg"
img_1 = prepare_image(img_path_1)
img_2 = prepare_image(img_path_2)

In [5]:
img_1.shape

(512, 512, 3)

In [12]:
input_shape

array([  1, 512, 512,   3], dtype=int32)

In [10]:
# Actual Data - this load input_data to the interpreter
input_shape = input_details[0]['shape']
input_data = img_1.reshape(input_shape) # the actual data

interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
#print(output_data.shape)
print(output_data)

[[[ 1.75625816e-01  8.27086717e-02  4.45459247e-01  2.40346387e-01]
  [ 1.40589505e-01  2.92905271e-01  6.32751703e-01  6.23045802e-01]
  [ 7.00924039e-01  2.03118339e-01  9.92613912e-01  6.94803953e-01]
  [ 1.25138670e-01  6.47781730e-01  7.88786650e-01  8.89877915e-01]
  [ 5.37755728e-01  2.07932830e-01  9.05364633e-01  6.43195570e-01]
  [ 3.51805121e-01  2.32024580e-01  8.08923244e-01  6.12208128e-01]
  [ 1.83966219e-01  5.73507369e-01  7.31984854e-01  8.56648505e-01]
  [ 7.34875500e-02  2.27252737e-01  4.64386374e-01  6.69251561e-01]
  [ 6.29345953e-01  3.32195252e-01  1.00952959e+00  7.82346845e-01]
  [-6.45785592e-04  6.25041306e-01  1.63918771e-02  8.26758683e-01]
  [ 9.91178453e-02  1.05838872e-01  4.01077896e-01  2.51949519e-01]
  [ 9.72360075e-02  3.86294425e-01  6.72855735e-01  7.66533554e-01]
  [ 2.45796740e-01  2.67944485e-01  4.24193323e-01  7.18096137e-01]
  [ 7.99796879e-02  5.37673354e-01  7.95043826e-01  7.77008891e-01]
  [ 2.20858306e-01  1.08725511e-01  5.41949153e-

In [105]:
# Actual Data - this load input_data to the interpreter
input_shape = input_details[0]['shape']
input_data = img_2.reshape(input_shape) # the actual data

interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
#print(output_data.shape)
print(output_data)

[[[ 9.1380477e-03  2.7907193e-01  3.8207453e-01  6.4072800e-01]
  [ 4.6251461e-01  1.7517757e-01  9.5467675e-01  7.1484441e-01]
  [ 4.3263823e-02  5.4687810e-01  5.2053916e-01  8.5734868e-01]
  [ 3.2435247e-01  2.2949073e-01  8.7405396e-01  8.2306468e-01]
  [ 5.1326597e-01  6.2288809e-01  7.8309941e-01  8.2136226e-01]
  [ 1.9971468e-01  7.2719336e-02  4.7037673e-01  3.6498329e-01]
  [ 6.4338595e-02  6.3797230e-01  6.4231682e-01  8.9148325e-01]
  [ 1.3228746e-01  1.9562842e-01  5.9647983e-01  6.2551123e-01]
  [ 5.3296137e-01  6.8425733e-01  7.8285074e-01  8.6250216e-01]
  [-1.9300520e-02  3.4475401e-01  4.0403086e-01  5.5276310e-01]
  [ 2.4886291e-01  1.1071661e-01  5.8930093e-01  4.8979166e-01]
  [ 2.9244381e-01  4.9193990e-01  8.1578702e-01  8.5394645e-01]
  [ 4.7493985e-01  5.4996610e-03  8.7843347e-01  8.9221179e-01]
  [ 6.4675045e-01  1.2501770e-01  9.5748544e-01  8.9715213e-01]
  [ 9.4212070e-03  2.4396174e-01  1.8242168e-01  6.8049729e-01]
  [ 4.6970278e-02  3.6838937e-01  4.8223

In [ ]:
# https://github.com/googleapis/python-automl/tree/19dd0a14998818ca8305c5c72a31228c74357433/samples/vision_edge/edge_container_predict